

import csv

import numpy as np
import sympy

from glassbox.analysis.verify_projection_gains import (
    EQUATIONS_CSV, E_PROBE, FEATURES, N_NU, N_W,
    eval_uT, first_harmonic, make_fn, tangential_gain_k,
)

OUT_TEX = "outputs/appendix_expressions.tex"


def harmonic_ev(fn):
    """Explained variance of {1, cos nu, sin nu} at dp=0, e=E_PROBE,
    averaged over periapsis angle w."""
    nu = np.linspace(0, 2 * np.pi, N_NU, endpoint=False)
    evs = []
    for w in np.linspace(0, 2 * np.pi, N_W, endpoint=False):
        f, g = E_PROBE * np.cos(w), E_PROBE * np.sin(w)
        u = eval_uT(fn, 0.0, f, g, w + nu)
        a0 = np.mean(u)
        a1 = 2 * np.mean(u * np.cos(nu))
        b1 = 2 * np.mean(u * np.sin(nu))
        fit = a0 + a1 * np.cos(nu) + b1 * np.sin(nu)
        ss_tot = np.sum((u - a0) ** 2)
        ss_res = np.sum((u - fit) ** 2)
        evs.append(1.0 if ss_tot == 0 else 1.0 - ss_res / ss_tot)
    return float(np.mean(evs))


def round_floats(expr, sig=4):
    return expr.xreplace({
        n: sympy.Float(f"{float(n):.{sig}g}")
        for n in expr.atoms(sympy.Float)
    })


def to_latex(eq_str):
    syms = sympy.symbols(FEATURES)
    loc = dict(zip(FEATURES, syms))
    loc["square"] = lambda x: x**2
    expr = sympy.sympify(eq_str, locals=loc)
    tex = sympy.latex(round_floats(expr), mul_symbol="dot")
    # readable feature names
    tex = tex.replace("cosL", r"\cos L").replace("sinL", r"\sin L")
    tex = tex.replace("dp", r"\delta p")
    return tex


def main():
    rows = list(csv.DictReader(open(EQUATIONS_CSV)))
    assert len(rows) == 15

    records = []
    for row in rows:
        fT = make_fn(row["uT_equation"])
        fR = make_fn(row["uR_equation"])
        k = tangential_gain_k(fT)
        A_cos, _ = first_harmonic(fT, "cos")
        sin_R, _ = first_harmonic(fR, "sin")
        R_cos, _ = first_harmonic(fR, "cos")
        records.append(dict(
            label=row["label"], k=k, A_cos=A_cos, G0=-sin_R, R_cos=R_cos,
            ev_T=harmonic_ev(fT), ev_R=harmonic_ev(fR),
            uT=row["uT_equation"], uR=row["uR_equation"],
        ))

    # ---- console summary ----
    print(f"{'label':<45} {'k':>7} {'A_cos':>7} {'G0':>6} {'R_cos':>6} "
          f"{'EV_T':>6} {'EV_R':>6}")
    for r in records:
        print(f"{r['label']:<45} {r['k']:>7.2f} {r['A_cos']:>7.2f} "
              f"{r['G0']:>6.2f} {r['R_cos']:>6.2f} "
              f"{r['ev_T']:>6.3f} {r['ev_R']:>6.3f}")
    ev_T = np.array([r["ev_T"] for r in records])
    ev_R = np.array([r["ev_R"] for r in records])
    print(f"\nEV_T: median {np.median(ev_T):.3f}, min {ev_T.min():.3f}")
    print(f"EV_R: median {np.median(ev_R):.3f}, min {ev_R.min():.3f}")

    # ---- LaTeX ----
    def short(label):
        return (label.replace("SAC_", "SAC ").replace(" / PySR seed", "/")
                .replace(" (+sqrt, wide search)", "$^{\\dagger\\ddagger}$")
                .replace(" (+sqrt)", "$^{\\dagger}$"))

    lines = []
    lines.append("% ---- generated by gen_expressions_appendix.py ----")
    lines.append(r"\begin{table}[h]")
    lines.append(r"  \centering")
    lines.append(r"  \caption{Per-run projected parameters ($\delta p = 0$ "
                 r"effective gains; Section~\ref{sec:structure}) and "
                 r"leading-harmonic explained variance (EV) of each "
                 r"expression at $\delta p = 0$, $e = 0.03$, averaged over "
                 r"periapsis angles. $R_{\cos}$ is the radial "
                 r"phase-contamination coefficient (ideally 0). "
                 r"$^{\dagger}$: $+\sqrt{\cdot}$ operator; "
                 r"$^{\ddagger}$: 900-iteration budget.}")
    lines.append(r"  \label{tab:per_run_params}")
    lines.append(r"  \small")
    lines.append(r"  \begin{tabular}{lrrrrrr}")
    lines.append(r"    \toprule")
    lines.append(r"    Run & $k$ & $A_{\cos}$ & $G_0$ & $R_{\cos}$ & "
                 r"EV($u_T$) & EV($u_R$) \\")
    lines.append(r"    \midrule")
    for r in records:
        lines.append(f"    {short(r['label'])} & {r['k']:.2f} & "
                     f"{r['A_cos']:.2f} & {r['G0']:.2f} & {r['R_cos']:.2f} & "
                     f"{r['ev_T']:.3f} & {r['ev_R']:.3f} \\\\")
    lines.append(r"    \bottomrule")
    lines.append(r"  \end{tabular}")
    lines.append(r"\end{table}")
    lines.append("")

    for r in records:
        lines.append(f"\\noindent\\textbf{{{short(r['label'])}}}:")
        lines.append(r"{\scriptsize\begin{align*}")
        lines.append(f"u_T &= {to_latex(r['uT'])} \\\\")
        lines.append(f"u_R &= {to_latex(r['uR'])}")
        lines.append(r"\end{align*}}")
        lines.append("")

    with open(OUT_TEX, "w") as fp:
        fp.write("\n".join(lines))
    print(f"\nwrote -> {OUT_TEX}")


if __name__ == "__main__":
    main()
